### ISSUE TITLE
Q1: How to use this saved .csv file to perform downstream analysis for IMC data?

### ISSUE THREAD

**Issue by HouPB** [BodenmillerGroup/napari-roi#10]
Hi, Milad,
I added a new ROI by napari-roi but I don't know how to use this csv file? which steps I will use it? Any suggestions are appreciated. 

Best regards,
pengbo

**Comment by Milad4849** [comment]
Hi Pengbo, 
Thanks for your question. I am not certain that I correctly understand your question. Is your question about the usage of napari-roi itself or about steps that come after regions have been selected using napari-roi?

**Comment by HouPB** [comment]
Thanks for your reply. I have selected the regions of interest by using napari-roi and output the final csv files. Yes, I want to know how to use this files when I run IMC data analysis workflow and which steps I will use it?

**Comment by nilseling** [comment]
Hi @HouPB 

have you selected the ROI on a panorama that you have previously acquired? If so you might be able to load the generated CSV into the Fluidigm software when you acquire your sample.

**Comment by HouPB** [comment]
Yes, I have selected it on a panorama. I am trying to use load this CSV by Fluidigm software. Thanks

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Nils ***@***.***>
发送时间: 2023年3月29日 15:39
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [BodenmillerGroup/napari-roi] Q1: How to use this saved .csv file to perform downstream analysis for IMC data? (Issue #10)


Hi @HouPB<https://github.com/HouPB>

have you selected the ROI on a panorama that you have previously acquired? If so you might be able to load the generated CSV into the Fluidigm software when you acquire your sample.

―

**Comment by nilseling** [comment]
It's probably better if you select the ROI directly in the Fluidigm software instead of using `napari-roi`.

**Comment by HouPB** [comment]
Yes, I agree with you, but my samples are aorta root and their shape is round or irregular. Just square and rectangle are provided in the Fluidigm software when I drawn a ROI before slide scanning

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Nils ***@***.***>
发送时间: 2023年3月29日 15:52
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [BodenmillerGroup/napari-roi] Q1: How to use this saved .csv file to perform downstream analysis for IMC data? (Issue #10)


It's probably better if you select the ROI directly in the Fluidigm software instead of using napari-roi.

―

**Comment by nilseling** [comment]
Ah, now I understand. You can't use the Fluidigm software to acquire any other shape than rectangular. Even if you select a round shape in `napari-roi`. There is unfortunately no way around measuring rectangular shapes.

**Comment by HouPB** [comment]
Haha. Anyway, I am grateful for your patient instruction. Hope someone or Fluidgm could handle this problem in the future.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Nils ***@***.***>
发送时间: 2023年3月29日 16:13
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [BodenmillerGroup/napari-roi] Q1: How to use this saved .csv file to perform downstream analysis for IMC data? (Issue #10)


Ah, now I understand. You can't use the Fluidigm software to acquire any other shape than rectangular. Even if you select a round shape in napari-roi. There is unfortunately no way around measuring rectangular shapes.

―

**Comment by nilseling** [comment]
That would be surprising if they manage to implement this feature ;) closing now
